// Customers
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_SHORT_CUSTOMERS = "GET_SHORT_CUSTOMERS";
export const CLEAR_CUSTOMERS = "CLEAR_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CURRENT_CUSTOMER = "CURRENT_CUSTOMER";
export const CLEAR_CURRENT_CUSTOMER = "CLEAR_CURRENT_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMER_ERROR = "CLEAR_CUSTOMER_ERROR";
export const SET_ONSCREEN_CUSTOMERS = "SET_ONSCREEN_CUSTOMERS";
export const CLEAR_ONSCREEN_CUSTOMERS = "CLEAR_ONSCREEN_CUSTOMERS";

// Customer creds
export const GET_CUSTOMER_CREDS = "GET_CUSTOMER_CREDS";
export const CLEAR_CUSTOMER_CREDS = "CLEAR_CUSTOMER_CREDS";
export const ADD_CUSTOMER_CRED = "ADD_CUSTOMER_CRED";
export const UPDATE_CUSTOMER_CRED = "UPDATE_CUSTOMER_CRED";
export const DELETE_CUSTOMER_CRED = "DELETE_CUSTOMER_CRED";
export const CURRENT_CUSTOMER_CRED = "CURRENT_CUSTOMER_CRED";
export const CLEAR_CURRENT_CUSTOMER_CRED = "CLEAR_CURRENT_CUSTOMER_CRED";
export const CUSTOMER_CRED_ERROR = "CUSTOMER_CRED_ERROR";
export const CLEAR_CUSTOMER_CRED_ERROR = "CLEAR_CUSTOMER_CRED_ERROR";
export const SET_ONSCREEN_CUSTOMER_CREDS = "SET_ONSCREEN_CUSTOMER_CREDS";
export const CLEAR_ONSCREEN_CUSTOMER_CREDS = "CLEAR_ONSCREEN_CUSTOMER_CREDS";

// Movie
export const GET_MOVIES = "GET_MOVIES";
export const GET_SHORT_MOVIES = "GET_SHORT_MOVIES";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const CURRENT_MOVIE = "CURRENT_MOVIE";
export const CLEAR_CURRENT_MOVIE = "CLEAR_CURRENT_MOVIE";
export const MOVIE_ERROR = "MOVIE_ERROR";
export const CLEAR_MOVIE_ERROR = "CLEAR_MOVIE_ERROR";
export const SET_ONSCREEN_MOVIES = "SET_ONSCREEN_MOVIES";
export const CLEAR_ONSCREEN_MOVIES = "CLEAR_ONSCREEN_MOVIES";

// Screen
export const GET_SCREENS = "GET_SCREENS";
export const GET_SHORT_SCREENS = "GET_SHORT_SCREENS";
export const CLEAR_SCREENS = "CLEAR_SCREENS";
export const ADD_SCREEN = "ADD_SCREEN";
export const UPDATE_SCREEN = "UPDATE_SCREEN";
export const DELETE_SCREEN = "DELETE_SCREEN";
export const CURRENT_SCREEN = "CURRENT_SCREEN";
export const CLEAR_CURRENT_SCREEN = "CLEAR_CURRENT_SCREEN";
export const SCREEN_ERROR = "SCREEN_ERROR";
export const CLEAR_SCREEN_ERROR = "CLEAR_SCREEN_ERROR";
export const SET_ONSCREEN_SCREENS = "SET_ONSCREEN_SCREENS";
export const CLEAR_ONSCREEN_SCREENS = "CLEAR_ONSCREEN_SCREENS";

// Screen tier
export const GET_SCREEN_TIERS = "GET_SCREEN_TIERS";
export const GET_SHORT_SCREEN_TIERS = "GET_SHORT_SCREEN_TIERS";
export const CLEAR_SCREEN_TIERS = "CLEAR_SCREEN_TIERS";
export const ADD_SCREEN_TIER = "ADD_SCREEN_TIER";
export const UPDATE_SCREEN_TIER = "UPDATE_SCREEN_TIER";
export const DELETE_SCREEN_TIER = "DELETE_SCREEN_TIER";
export const CURRENT_SCREEN_TIER = "CURRENT_SCREEN_TIER";
export const CLEAR_CURRENT_SCREEN_TIER = "CLEAR_CURRENT_SCREEN_TIER";
export const SCREEN_TIER_ERROR = "SCREEN_TIER_ERROR";
export const CLEAR_SCREEN_TIER_ERROR = "CLEAR_SCREEN_TIER_ERROR";
export const SET_ONSCREEN_SCREEN_TIERS = "SET_ONSCREEN_SCREEN_TIERS";
export const CLEAR_ONSCREEN_SCREEN_TIERS = "CLEAR_ONSCREEN_SCREEN_TIERS";

// Seat
export const GET_SEATS = "GET_SEATS";
export const GET_SHORT_SEATS = "GET_SHORT_SEATS";
export const CLEAR_SEATS = "CLEAR_SEATS";
export const ADD_SEAT = "ADD_SEAT";
export const UPDATE_SEAT = "UPDATE_SEAT";
export const DELETE_SEAT = "DELETE_SEAT";
export const CURRENT_SEAT = "CURRENT_SEAT";
export const CLEAR_CURRENT_SEAT = "CLEAR_CURRENT_SEAT";
export const SEAT_ERROR = "SEAT_ERROR";
export const CLEAR_SEAT_ERROR = "CLEAR_SEAT_ERROR";
export const SET_ONSCREEN_SEATS = "SET_ONSCREEN_SEATS";
export const CLEAR_ONSCREEN_SEATS = "CLEAR_ONSCREEN_SEATS";

// Seat type
export const GET_SEAT_TYPES = "GET_SEAT_TYPES";
export const GET_SHORT_SEAT_TYPES = "GET_SHORT_SEAT_TYPES";
export const CLEAR_SEAT_TYPES = "CLEAR_SEAT_TYPES";
export const ADD_SEAT_TYPE = "ADD_SEAT_TYPE";
export const UPDATE_SEAT_TYPE = "UPDATE_SEAT_TYPE";
export const DELETE_SEAT_TYPE = "DELETE_SEAT_TYPE";
export const CURRENT_SEAT_TYPE = "CURRENT_SEAT_TYPE";
export const CLEAR_CURRENT_SEAT_TYPE = "CLEAR_CURRENT_SEAT_TYPE";
export const SEAT_TYPE_ERROR = "SEAT_TYPE_ERROR";
export const CLEAR_SEAT_TYPE_ERROR = "CLEAR_SEAT_TYPE_ERROR";
export const SET_ONSCREEN_SEAT_TYPES = "SET_ONSCREEN_SEAT_TYPES";
export const CLEAR_ONSCREEN_SEAT_TYPES = "CLEAR_ONSCREEN_SEAT_TYPES";

// Showing
export const GET_SHOWINGS = "GET_SHOWINGS";
export const GET_SHORT_SHOWINGS = "GET_SHORT_SHOWINGS";
export const CLEAR_SHOWINGS = "CLEAR_SHOWINGS";
export const ADD_SHOWING = "ADD_SHOWING";
export const UPDATE_SHOWING = "UPDATE_SHOWING";
export const DELETE_SHOWING = "DELETE_SHOWING";
export const CURRENT_SHOWING = "CURRENT_SHOWING";
export const CLEAR_CURRENT_SHOWING = "CLEAR_CURRENT_SHOWING";
export const SHOWING_ERROR = "SHOWING_ERROR";
export const CLEAR_SHOWING_ERROR = "CLEAR_SHOWING_ERROR";
export const SET_ONSCREEN_SHOWINGS = "SET_ONSCREEN_SHOWINGS";
export const CLEAR_ONSCREEN_SHOWINGS = "CLEAR_ONSCREEN_SHOWINGS";

// Staff
export const GET_STAFFS = "GET_STAFFS";
export const GET_SHORT_STAFFS = "GET_SHORT_STAFFS";
export const CLEAR_STAFFS = "CLEAR_STAFFS";
export const ADD_STAFF = "ADD_STAFF";
export const UPDATE_STAFF = "UPDATE_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
export const CURRENT_STAFF = "CURRENT_STAFF";
export const CLEAR_CURRENT_STAFF = "CLEAR_CURRENT_STAFF";
export const STAFF_ERROR = "STAFF_ERROR";
export const CLEAR_STAFF_ERROR = "CLEAR_STAFF_ERROR";
export const SET_ONSCREEN_STAFFS = "SET_ONSCREEN_STAFFS";
export const CLEAR_ONSCREEN_STAFFS = "CLEAR_ONSCREEN_STAFFS";

// Staff creds
export const GET_STAFF_CREDS = "GET_STAFF_CREDS";
export const CLEAR_STAFF_CREDS = "CLEAR_STAFF_CREDS";
export const ADD_STAFF_CRED = "ADD_STAFF_CRED";
export const UPDATE_STAFF_CRED = "UPDATE_STAFF_CRED";
export const DELETE_STAFF_CRED = "DELETE_STAFF_CRED";
export const CURRENT_STAFF_CRED = "CURRENT_STAFF_CRED";
export const CLEAR_CURRENT_STAFF_CRED = "CLEAR_CURRENT_STAFF_CRED";
export const STAFF_CRED_ERROR = "STAFF_CRED_ERROR";
export const CLEAR_STAFF_CRED_ERROR = "CLEAR_STAFF_CRED_ERROR";
export const SET_ONSCREEN_STAFF_CREDS = "SET_ONSCREEN_STAFF_CREDS";
export const CLEAR_ONSCREEN_STAFF_CREDS = "CLEAR_ONSCREEN_STAFF_CREDS";

// Ticket
export const GET_TICKETS = "GET_TICKETS";
export const GET_SHORT_TICKETS = "GET_SHORT_TICKETS";
export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const CURRENT_TICKET = "CURRENT_TICKET";
export const CLEAR_CURRENT_TICKET = "CLEAR_CURRENT_TICKET";
export const TICKET_ERROR = "TICKET_ERROR";
export const CLEAR_TICKET_ERROR = "CLEAR_TICKET_ERROR";
export const SET_ONSCREEN_TICKETS = "SET_ONSCREEN_TICKETS";
export const CLEAR_ONSCREEN_TICKETS = "CLEAR_ONSCREEN_TICKETS";